### ISSUE TITLE
Springboot3 + MyBatis ExceptionInInitializerError

### ISSUE THREAD

**Issue by Bahramudin** [mybatis/spring-native#94] opened 2023-04-26 12:27 UTC
I want to use GraalVM to compile Springboot3 (version 3.0.6) project with MyBatis3 (version 3.5.13), the compile process finished successfully, but when I run the generated .exe file, it throws the following error:

```
java.lang.ExceptionInInitializerError: null
        at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:363) ~[web.exe:3.0.1]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:344) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:145) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:747) ~[web.exe:6.0.8]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:565) ~[web.exe:6.0.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[web.exe:3.0.6]
        at com.adil.bms.web.BmsApplication.main(BmsApplication.java:19) ~[web.exe:na]
Caused by: org.apache.ibatis.logging.LogException: Error creating logger for logger org.mybatis.spring.mapper.ClassPathMapperScanner.  Cause: java.lang.NullPointerException
        at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:54) ~[na:na]
        at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:47) ~[na:na]
        at org.mybatis.logging.LoggerFactory.getLogger(LoggerFactory.java:32) ~[na:na]
        at org.mybatis.spring.mapper.ClassPathMapperScanner.<clinit>(ClassPathMapperScanner.java:61) ~[na:na]
        ... 12 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.apache.ibatis.logging.LogFactory.getLog(LogFactory.java:52) ~[na:na]
        ... 15 common frames omitted
```

Is there any configuration I am missing? 
Thanks!

**Comment by hazendaz** [comment] 2023-04-27 03:00
issue has been reported in a few places already.  Haven't had time to look into it but plan to do so.  We have a very odd logging framework solution built into mybatis that allows users to use many different loggers.  I've always been personally against that as it may have made sense 15 years ago but now it doesn't quite make much sense.  For now on 3.5.x, no plan to really do much about that but will look to see if I can figure out what is going on there.

**Comment by Bahramudin** [comment] 2023-04-27 19:30
@hazendaz Hmm, so it means that MyBatis has no plan to participate in spring-native which compiles by GraalVM to generate OS native machine code?!
If so, then what can be the replacement for MyBatis technology to generate native machine code in the near future?

**Comment by hazendaz** [comment] 2023-04-28 00:15
Sorry reference was that we don't plan to use more standard logging solution in 3.5.x.  I didn't mean to imply we won't fix the issue we have in 3.5.x.  I was just noting our logic there is already not what would normally be expected.

The issue itself, I haven had time to look to see what the issue is or how to resolve.  If it were to say remove our logger solution, it would come in 3.6.x.  that change would be big and breaking for users and need more discussion.  If it's something otherwise simple it will happen in 3.5.x.

We certainly welcome all help in this area.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bahramudin** [comment] 2023-04-28 01:02
@hazendaz Thanks! I hope this problem gets solved as soon as possible, I am also thinking about how to achieve this functionality, whenever there is any good idea, I will share it here.

**Comment by hazendaz** [comment] 2023-04-28 01:34
one other thing to note: this project hasn't even seen a release yet.  So its still on spring boot 2.  I think it needs additional work before spring boot 3 and probably needs a release on spring boot 2.  Not sure as not one I worked on other than PRs from renovate.  But think that is the case.  We will need both.  If I understand spring native changed quite a bit in 3. So there is probably a lot of work to do.

**Comment by hazendaz** [comment] 2023-04-28 01:38
@Bahramudin What logger are you using?

**Comment by hazendaz** [comment] 2023-04-28 01:39
assuming since noted spring boot 3, slfj4 2 as may be something in how we are trying to detect logging.

**Comment by Bahramudin** [comment] 2023-04-28 18:42
@hazendaz I am using Springboot3 default logger (slfj4), but the amazing point for me is why if do not use MyBatis in my project, it compiles and run without any problem (I have tested with some other frameworks like: Thymeleaf and some FrondEnd frameworks it was all working well, but only with MyBatis it was not working). If the problem is really related with logging system, then why Springboot3 not crashing when run the program?

**Comment by hazendaz** [comment] 2023-04-29 01:48
It's the mybatis logging system.  It was not designed to use one logger such as slf4j.  Instead, it reads the classpath or config item to figure out what logger is being used and directly uses that logger.  That's the bit I eventually want to just delete.  There are only 183 or so invokes of any logger in mybatis core and unless I'm mistaken every single extension, we support is slf4j based.  So, it's a bit overkill in design.  It probably was rooted in some issue in 2000s with loggers but slf4j and log4j2 rewire to anything making the exercise pointless support that has zero to do with mybatis existing.

That said, intent is to delete that at mybatis 3.6.0 if broader group all agrees with me.

Until then my option is to try to resolve it at 3.5.x or just move onto 3.6.0 and work out concerns.

Now, the likely issue probably is due to the service loader change in slf4j 2.  The code in mybatis was designed with earlier versions and even has long obsolete slf4j 1.6 support.  So, my gut tells me that even though we build against slf4j2 our detection is either incorrect for 2.0 or its deeper in how it's trying to figure out classpath.  I'm leaning towards classpath detection issue here or someone would have complained about broken logs by now.  In fact all usage I know about at my day job uses slf4j 2 now outside of more limited spring boot 2 usage of version 2.

To that end, I've got no experience with spring native.  So maybe classpath detection is simply bad.  Further I see statements around aot and fact our reflection must change.

So...now I've rewritten all our logs last night to match more modern slf4j style to remove all string concatenation.   I found a few spots where code looked wrong and could also contribute to issues.  I'm going to try to get the changes I'm doing now in sometime this weekend.

Likely we need to partner a bit here.  We release all our snapshots to sonatype so if you could test once I start getting updates out it will help in either outright resolving in our current form or force my suggested deletion of this code rather soon.

Have you tried setting mybatis config to use slf4j setting?  I think that may avoid the issues it's not trying to figure it out at runtime.


Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Bahramudin** [comment] 2023-04-29 21:00
@hazendaz Hi, hope everything going well with you! Here I have tested switching the logging to SLF4J by the following set of MyBatis:
```log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl```, but the result was the same, again throwing the same error, and also I tried to set the log-impl to NO_LOGGING as MyBatis configuration documentation, but it was throwing the Exception cannot covert String NO_LOGGING to some class.

I think you can turn off the logging functionality first or set a flag that can be controlled by the configuration file on whether to use logging. Usually in dev mode, the flag is set to true, and when comes to prod mode, we set the flag to false, you there just check the flag, if it is false, then do nothing with logging.

And here I am ready to test the snapshot version, you can do your changes, here I will test it, and any results I will share here.

**Comment by Bahramudin** [comment] 2023-05-14 23:35
@hazendaz Hi, did you do some changes to the project? I am ready to test the Snapshot version.

**Comment by kazuki43zoo** [comment] 2023-05-15 12:03
@Bahramudin 

Please try https://github.com/mybatis/spring-boot-starter/wiki/Quick-Start-for-building-native-image.
We have a plan to provide support classes for building native-image with spring-boot 3  on this project or mybatis-spring.

**Comment by Bahramudin** [comment] 2023-05-15 21:20
@kazuki43zoo Thanks for your efforts, that is nice to hear that MyBatis starts to support native-compile. But here when I put the configuration file into my project, and then run the application, it shows error:
```
Error: Could not find or load main class com.adil.test.web.TestApplication
Caused by: java.lang.ClassNotFoundException: com.adil.test.web.TestApplication
```
Is there any extra configuration I need to do?
Thanks!

**Comment by kazuki43zoo** [comment] 2023-05-15 22:51
Could you provide a repro project ?

**Comment by Bahramudin** [comment] 2023-05-18 19:12
@kazuki43zoo I did some research on this error, and finally find a way to run the project, it is to run I can run the project after packing (not native), but when I directly run the project from IDE, it was not working.
Although the server started successfully, some mapper not working well, it was null.
And then I compiled the project using this command ```mvn -Pnative native:compile -DskipTests```, the compile process was successful, and ```.exe``` file was successfully created, but when I run the file, I got the new error:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'userPrincipalDetailsServiceImpl': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'addressServiceImpl': Unsatisfied dependency expressed through field 'baseMapper': Error creating bean with name 'addressMapper': Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
2023-05-17T22:45:17.129+04:30  INFO 17844 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-05-17T22:45:17.133+04:30 ERROR 17844 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'userPrincipalDetailsServiceImpl': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'addressServiceImpl': Unsatisfied dependency expressed through field 'baseMapper': Error creating bean with name 'addressMapper': Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:343) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:267) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[web.exe:6.0.8]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[web.exe:6.0.8]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[web.exe:6.0.8]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[web.exe:6.0.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[web.exe:3.0.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[web.exe:3.0.6]
        at com.adil.bms.web.BmsApplication.main(BmsApplication.java:21) ~[web.exe:na]
```
So you can see the error if can guess what is causing this error? I have searched but did not find any solution.

**Comment by kazuki43zoo** [comment] 2023-05-18 21:49
@Bahramudin Please provide a repro project for investigating it.

**Comment by Bahramudin** [comment] 2023-05-19 21:14
@kazuki43zoo [this](https://github.com/Bahramudin/native-test) is a test repository. Compile was success, but run was error.
I used this ```mvn -Pnative native:compile -DskipTests``` to compile the project. And get the below error:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.0)

2023-05-20T01:36:39.597+04:30  INFO 18864 --- [           main] com.adil.NativeTestApplication           : Starting AOT-processed NativeTestApplication using Java 17.0.6 with PID 18864 (D:\BMS-v2\native-test\target\native-test.exe started by bahra in D:\BMS-v2\native-test\target)
2023-05-20T01:36:39.604+04:30  INFO 18864 --- [           main] com.adil.NativeTestApplication           : No active profile set, falling back to 1 default profile: "default"
2023-05-20T01:36:39.746+04:30  INFO 18864 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-05-20T01:36:39.747+04:30  INFO 18864 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-05-20T01:36:39.754+04:30  INFO 18864 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.8]
2023-05-20T01:36:39.774+04:30  INFO 18864 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-05-20T01:36:39.774+04:30  INFO 18864 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 169 ms
2023-05-20T01:36:39.792+04:30  WARN 18864 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userController': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper': Error creating bean with name 'userMapper': Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
2023-05-20T01:36:39.792+04:30  INFO 18864 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-05-20T01:36:39.794+04:30 ERROR 18864 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userController': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper': Error creating bean with name 'userMapper': Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:315) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArguments(BeanInstanceSupplier.java:258) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:198) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[native-test.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941) ~[native-test.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[native-test.exe:6.0.9]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[native-test.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[native-test.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[native-test.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[native-test.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[native-test.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[native-test.exe:3.1.0]
        at com.adil.NativeTestApplication.main(NativeTestApplication.java:13) ~[native-test.exe:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper': Error creating bean with name 'userMapper': Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:195) ~[na:na]
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveAndSet(AutowiredFieldValueResolver.java:167) ~[na:na]
        at com.adil.service.impl.UserServiceImpl__Autowiring.apply(UserServiceImpl__Autowiring.java:14) ~[na:na]
        at org.springframework.beans.factory.support.InstanceSupplier$1.get(InstanceSupplier.java:83) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888) ~[na:na]
        at org.springframework.beans.factory.support.RegisteredBean.resolveAutowiredArgument(RegisteredBean.java:219) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:312) ~[na:na]
        ... 21 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userMapper': Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.aot.AutowiredFieldValueResolver.resolveValue(AutowiredFieldValueResolver.java:189) ~[na:na]
        ... 39 common frames omitted
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
        at org.springframework.util.Assert.notNull(Assert.java:204) ~[na:na]
        at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:125) ~[native-test.exe:3.0.1]
        at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73) ~[native-test.exe:3.0.1]
        at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[native-test.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[native-test.exe:6.0.9]
        ... 49 common frames omitted
```

**Comment by kazuki43zoo** [comment] 2023-05-20 01:00
@Bahramudin 
If use the @MapperScan, please see https://github.com/mybatis/spring-native/blob/master/docs/src/site/markdown/index.md#using-mapperscan.

**You use the mybatis-plus, but the mybatis-plus is 3rd party module(no belong in MyBatis organization). Therefore the MyBatis team cannot support and resolve a problem of mybatis-plus.**

**Note:**
I added the `sqlSessionTemplateRef`, reporting error can resolved but occur the following error. This error does not belong MyBatis's module, please resolve by yourself. Thanks.

```
...
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[native-test:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[native-test:6.0.9]
        ... 77 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.baomidou.mybatisplus.core.MybatisXMLLanguageDriver.<init>()
        at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[native-test:na]
        at java.base@17.0.7/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754) ~[native-test:na]
        at org.apache.ibatis.scripting.LanguageDriverRegistry.lambda$register$0(LanguageDriverRegistry.java:38) ~[native-test:3.5.13]
        ... 94 common frames omitted
```

P.S:
Above error can fix adding reflection hint as follow:

```
      Stream.of(MybatisXMLLanguageDriver.class)
          .forEach(x -> hints.reflection().registerType(x, MemberCategory.values()));
```

But you meet next error as follow:

```
...
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[native-test:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[native-test:6.0.9]
        ... 49 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.baomidou.mybatisplus.core.metadata.TableInfo.chooseSelect(TableInfo.java:259) ~[native-test:3.5.3.1]
        at com.baomidou.mybatisplus.core.metadata.TableInfo.getAllSqlSelect(TableInfo.java:247) ~[native-test:3.5.3.1]
        at com.baomidou.mybatisplus.core.injector.AbstractMethod.sqlSelectColumns(AbstractMethod.java:162) ~[native-test:3.5.3.1]
        at com.github.yulichang.method.mp.SelectOne.sqlSelectColumns(SelectOne.java:44) ~[na:na]
        at com.baomidou.mybatisplus.core.injector.methods.SelectOne.injectMappedStatement(SelectOne.java:49) ~[native-test:3.5.3.1]
        at com.github.yulichang.method.mp.SelectOne.injectMappedStatement(SelectOne.java:32) ~[na:na]
        at com.baomidou.mybatisplus.core.injector.AbstractMethod.inject(AbstractMethod.java:80) ~[native-test:3.5.3.1]
        at com.baomidou.mybatisplus.core.injector.AbstractSqlInjector.lambda$inspectInject$0(AbstractSqlInjector.java:52) ~[native-test:3.5.3.1]
        at java.base@17.0.7/java.util.ArrayList.forEach(ArrayList.java:1511) ~[native-test:na]
        at com.baomidou.mybatisplus.core.injector.AbstractSqlInjector.inspectInject(AbstractSqlInjector.java:52) ~[native-test:3.5.3.1]
        at com.github.yulichang.injector.MPJSqlInjector.inspectInject(MPJSqlInjector.java:123) ~[native-test:na]
        at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parserInjector(MybatisMapperAnnotationBuilder.java:133) ~[na:na]
        at com.baomidou.mybatisplus.core.MybatisMapperAnnotationBuilder.parse(MybatisMapperAnnotationBuilder.java:123) ~[na:na]
        at com.baomidou.mybatisplus.core.MybatisMapperRegistry.addMapper(MybatisMapperRegistry.java:94) ~[na:na]
        at com.baomidou.mybatisplus.core.MybatisConfiguration.addMapper(MybatisConfiguration.java:129) ~[native-test:3.5.3.1]
        at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:80) ~[native-test:3.0.1]
        ... 52 common frames omitted
```

Above error occur at mybatisplus module, please submit a new issue to mybatis-plus.

**Closed by kazuki43zoo** 2023-05-20 01:00 UTC
Labels: waiting for feedback

**Comment by juujuu-waiyan** [comment] 2024-01-16 02:42
@kazuki43zoo 
I got this same error, should I used MyBatis for springboot 3 and GraalVM ?

**Comment by hazendaz** [comment] 2024-01-20 05:46
I think the native project here is not only not completely up to date as some native stuff changed but also most of our samples are failing. If someone with experience here could raise some PRs and fix our build it might be viable we can help out.  I know @kazuki43zoo knows more here but like most we are all busy with other things and speaking for myself, we are not remotely ready at work to even use native at all.  So really anyone that is working in this area that can contribute will help this move along.
